### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by ajsb85** [nexus-uw/vscode-gtm#7]
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined

```
property 'document' of undefined
    at C:\Users\username\.vscode\extensions\s3ramsay.vscode-gtm-0.0.3\out\src\extension.js:48:88
```

VS Code v1.4

**Comment by con-ssc** [comment]
I second that for vscode 1.5x
![image](https://cloud.githubusercontent.com/assets/8189808/18664270/28d57d6e-7f22-11e6-8004-6fc70311e8a4.png)

**Comment by mschenk42** [comment]
Are you still getting this error?  If so, can you provide some insights into how to reproduce?  Uninstalling and reinstalling the plugin may resolve this issue.
